global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['0.0.0.0:8080']
  - job_name: golang 
    metrics_path: /metrics
    static_configs:
      - targets:
        - 0.0.0.0:8080
        # GCloud Run - webinar-vfm2ipcttq-uw.a.run.app