global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:8080']
  - job_name: golang 
    metrics_path: /metrics
    static_configs:
      - targets:
        - golang:8080
        # GCloud Run - webinar-vfm2ipcttq-uw.a.run.app